core_case_data:
  api:
    url:  "http://localhost:4452"
idam:
  s2s-auth: "http://localhost:4552"
  api:
    url: "http://localhost:8080"
  users:
    sscs:
      username: bulkscanorchestrator+systemupdate@gmail.com
      password: Password12

queue:
  connection-string: Endpoint=sb://bulk-scan-servicebus-kevin.servicebus.windows.net/;SharedAccessKeyName=listen;SharedAccessKey=UCZjqc2I0Dki6nk6oJjY51xYL279O2sO+gEY4Ouo7ko=;EntityPath=envelopes
  read-interval: 100
