---
java:
  name: ${SERVICE_NAME}
  image: ${IMAGE_NAME}
  applicationPort: 8582
  cpuRequests: 200m
  readinessDelay: 45
  livenessDelay: 45
  ingressHost: ${SERVICE_FQDN}  
  environment:
    S2S_SECRET: "${S2S_SECRET}"
    IDAM_CLIENT_SECRET: "${IDAM_CLIENT_SECRET}"
    IDAM_USERS_BULKSCAN_USERNAME: "${IDAM_USER_NAME}"
    IDAM_USERS_BULKSCAN_PASSWORD: "${IDAM_USER_PASSWORD}"
  configmap:
    LOGBACK_REQUIRE_ALERT_LEVEL: "false"
    LOGBACK_REQUIRE_ERROR_CODE: "false"
    S2S_NAME: "bulk_scan_orchestrator"
  secrets:
    QUEUE_CONNECTION_STRING:
      secretRef: servicebus-secret-queue-$SERVICE_NAME-envelopes
      key: connectionString
servicebus:
  resourceGroup: bulk-scan-aks
  setup:
    queues:
     - name: envelopes
